export const FETCH_VEHICLE_MAKES = "FETCH_VEHICLE_MAKES";
export const FETCH_VEHICLE_MODELS = "FETCH_VEHICLE_MODELS";
export const FETCH_VEHICLES = "FETCH_VEHICLES";
export const SET_VEHICLE_MAKE = "SET_VEHICLE_MAKE";
export const SET_VEHICLE_MODEL = "SET_VEHICLE_MODEL";
export const RESET_SELECTION = "RESET_SELECTION";
export const ERROR_OCCURRED = "ERROR_OCCURRED";
