export const DISPLAY_MODULES = "DISPLAY_MODULES";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART";
export const DISPLAY_CART_CONTENTS = "DISPLAY_CART_CONTENTS";
