export const FETCH_GAME_LIST = "FETCH_GAME_LIST";
export const SET_GAME_RATING = "SET_GAME_RATING";
export const SORT_GAMES_BY_RATING = "SORT_GAMES_BY_RATING";
export const RANDOMLY_RATE = "RANDOMLY_RATE";
